In [1]:
import pandas as pd
import numpy as np

In [3]:
pd.read_csv("junction/Junction_Data.csv", nrows=1000, delimiter=';')

,Receipt,TransactionDate,BeginHour,EAN,Quantity,PersonAgeGrp,KCustomer,QualClass,EasyClass
0,13735389,2017-01-01,21,4001724819608,"1,000000",NaN,6713,Q_8-10,E_4-7
1,13735389,2017-01-01,21,6411402197108,"1,000000",NaN,6713,Q_8-10,E_4-7
2,13735438,2017-01-01,13,6411402202208,"1,000000",65-,6715,Q_4-7,E_1-3
3,13735438,2017-01-01,13,6407810016636,"1,000000",65-,6715,Q_4-7,E_1-3
4,13735438,2017-01-01,13,6416046654123,"1,000000",65-,6715,Q_4-7,E_1-3
5,13735438,2017-01-01,13,2000619500005,"0,844000",65-,6715,Q_4-7,E_1-3
6,13735438,2017-01-01,13,6408430310869,"1,000000",65-,6715,Q_4-7,E_1-3
7,13735438,2017-01-01,13,2000797000007,"0,996000",65-,6715,Q_4-7,E_1-3
8,13735438,2017-01-01,13,5410146414497,"1,000000",65-,6715,Q_4-7,E_1-3
9,13735438,2017-01-01,13,8718114868943,"1,000000",65-,6715,Q_4-7,E_1-3
10,13735438,2017-01-01,13,6408430000548,"1,000000",65-,6715,Q_4-7,E_1-3
11,13735438,2017-01-01,13,6409290001492,"1,000000",65-,6715,Q_4-7,E_1-3
12,13735613,2017-01-01,15,7622100936077,"1,000000",65-,6713,Q_4-7,E_4-7
13,13735669,2017-01-01,12,6406510092667,"1,000000",25-34,6711,Q_1-3,E_4-7
14,13735669,2017-01-01,12,6420256001783,"1,000000",25-34,6711,Q_1-3,E_4-7
15,13735669,2017-01-01,12,73130710,"1,000000",25-34,6711,Q_1-3,E_4-7
16,13735676,2017-01-01,17,6417964574982,"1,000000",25-34,6712,Q_8-10,E_4-7
17,13735676,2017-01-01,17,6424200014614,"1,000000",25-34,6712,Q_8-10,E_4-7
18,13735676,2017-01-01,17,6410402020669,"1,000000",25-34,6712,Q_8-10,E_4-7
19,13735676,2017-01-01,17,2000600200006,"0,046000",25-34,6712,Q_8-10,E_4-7
20,13735676,2017-01-01,17,6410405155580,"1,000000",25-34,6712,Q_8-10,E_4-7
21,13735676,2017-01-01,17,5711953002311,"1,000000",25-34,6712,Q_8-10,E_4-7
22,13735676,2017-01-01,17,6408641155914,"2,000000",25-34,6712,Q_8-10,E_4-7
23,13735676,2017-01-01,17,6410405075796,"1,000000",25-34,6712,Q_8-10,E_4-7
24,13735676,2017-01-01,17,6410405136602,"1,000000",25-34,6712,Q_8-10,E_4-7
25,13735676,2017-01-01,17,2000615100001,"0,072000",25-34,6712,Q_8-10,E_4-7
26,13735704,2017-01-01,21,4001724819905,"1,000000",18-24,6712,Q_4-7,E_4-7
27,13735704,2017-01-01,21,7310616071503,"1,000000",18-24,6712,Q_4-7,E_4-7
28,13735704,2017-01-01,21,6430056280196,"1,000000",18-24,6712,Q_4-7,E_4-7
29,13735704,2017-01-01,21,7393481006214,"1,000000",18-24,6712,Q_4-7,E_4-7
...,...,...,...,...,...,...,...,...,...
970,13766154,2017-01-01,21,6410405145567,"1,000000",35-44,6712,Q_4-7,E_4-7
971,13766154,2017-01-01,21,6405304002356,"1,000000",35-44,6712,Q_4-7,E_4-7
972,13766154,2017-01-01,21,6410405169679,"1,000000",35-44,6712,Q_4-7,E_4-7
973,13766161,2017-01-01,13,7312930000382,"1,000000",25-34,6712,Q_8-10,E_1-3
974,13766161,2017-01-01,13,6410405085627,"1,000000",25-34,6712,Q_8-10,E_1-3
975,13766952,2017-01-01,16,6416021001607,"2,000000",25-34,6711,Q_8-10,E_1-3
976,13766952,2017-01-01,16,6432700200123,"1,000000",25-34,6711,Q_8-10,E_1-3
977,13766952,2017-01-01,16,6411402164902,"1,000000",25-34,6711,Q_8-10,E_1-3
978,13766952,2017-01-01,16,6413200330206,"1,000000",25-34,6711,Q_8-10,E_1-3
979,13766952,2017-01-01,16,6410405149725,"1,000000",25-34,6711,Q_8-10,E_1-3
980,13766952,2017-01-01,16,2000518500007,"0,707000",25-34,6711,Q_8-10,E_1-3
981,13766952,2017-01-01,16,6415350002118,"2,000000",25-34,6711,Q_8-10,E_1-3
982,13766952,2017-01-01,16,5760466987783,"2,000000",25-34,6711,Q_8-10,E_1-3
983,13766952,2017-01-01,16,6413200340205,"1,000000",25-34,6711,Q_8-10,E_1-3
984,13766952,2017-01-01,16,8712566934744,"1,000000",25-34,6711,Q_8-10,E_1-3
985,13766952,2017-01-01,16,6407720025070,"1,000000",25-34,6711,Q_8-10,E_1-3
986,13766952,2017-01-01,16,6408430041312,"2,000000",25-34,6711,Q_8-10,E_1-3
987,13766952,2017-01-01,16,6412000016570,"1,000000",25-34,6711,Q_8-10,E_1-3
988,13766952,2017-01-01,16,5060107330368,"1,000000",25-34,6711,Q_8-10,E_1-3
989,13766952,2017-01-01,16,5760466630245,"1,000000",25-34,6711,Q_8-10,E_1-3
990,13766952,2017-01-01,16,2000753600005,"0,323000",25-34,6711,Q_8-10,E_1-3
991,13766952,2017-01-01,16,6430055270037,"1,000000",25-34,6711,Q_8-10,E_1-3
992,13766952,2017-01-01,16,6408430000524,"1,000000",25-34,6711,Q_8-10,E_1-3
993,13766952,2017-01-01,16,5410188009439,"1,000000",25-34,6711,Q_8-10,E_1-3
994,13766952,2017-01-01,16,4062300014985,"1,000000",25-34,6711,Q_8-10,E_1-3
995,13766952,2017-01-01,16,7310100962300,"1,000000",25-34,6711,Q_8-10,E_1-3
996,13766952,2017-01-01,16,2000642500003,"0,345000",25-34,6711,Q_8-10,E_1-3
997,13766952,2017-01-01,16,8076809521581,"1,000000",25-34,6711,Q_8-10,E_1-3
998,13766952,2017-01-01,16,6410402024247,"2,000000",25-34,6711,Q_8-10,E_1-3
999,13766952,2017-01-01,16,5060107330276,"1,000000",25-34,6711,Q_8-10,E_1-3

In [ ]:
def request(req_type="POST", url):
    headers = {
        'Ocp-Apim-Subscription-Key': '{subscription key}',
    }

    params = urllib.parse.urlencode({
    })

    try:
        conn = http.client.HTTPSConnection('kesko.azure-api.net')
        conn.request(req_type, "/files/store_services?%s" % params, "{body}", headers)
        response = conn.getresponse()
        data = response.read()
        print(data)
        conn.close()
    except Exception as e:
        print("[Errno {0}] {1}".format(e.errno, e.strerror))

In [19]:
import http.client, urllib.request, urllib.parse, urllib.error, base64
key = '7cfcc232a2294794815127a7dcfc9b73'

headers = {
    'Ocp-Apim-Subscription-Key': '{}'.format(key),
}

params = urllib.parse.urlencode({
})

try:
    conn = http.client.HTTPSConnection('kesko.azure-api.net')
    conn.request("POST", "/files/store_services?%s" % params, "{body}", headers)
    response = conn.getresponse()
    data = response.read()
    print(data)
    conn.close()
except Exception as e:
    print("[Errno {0}] {1}".format(e.errno, e.strerror))

b'{"uri":"https://keskojunction.file.core.windows.net/data/Junction-Kesko-store_services.xlsx?st=2018-11-24T09%3A19%3A50Z&se=2018-11-24T09%3A34%3A50Z&sp=r&sv=2018-03-28&sr=f&sig=ue%2BpAH23GZ8NXAFm5vCYJyJfBOgp6QwbB0xyVjhZyaI%3D","expires_at":"2018-11-24T09:34:50.998Z"}'

In [27]:

def get_name_by_ean_and_storeid(ean='5060107330368', store_id='K171', key='7cfcc232a2294794815127a7dcfc9b73'):
    headers = {
        # Request headers
        'Ocp-Apim-Subscription-Key': '{}'.format(key),
    }

    params = urllib.parse.urlencode({
    })

    try:
        conn = http.client.HTTPSConnection('kesko.azure-api.net')
        conn.request("GET", "/products/{storeId}/{ean}?%s".format(storeId=store_id, ean=ean) % params, "{body}", headers)
        response = conn.getresponse()
        data = response.read()
        print(data)
        conn.close()
    except Exception as e:
        print("[Errno {0}] {1}".format(e.errno, e.strerror))

In [43]:
def get_store_info_by_storeid(store_id='K171', key='7cfcc232a2294794815127a7dcfc9b73'):
    headers = {
        # Request headers
        'Ocp-Apim-Subscription-Key': '{}'.format(key),
    }

    params = urllib.parse.urlencode({
    })

    try:
        conn = http.client.HTTPSConnection('kesko.azure-api.net')
        conn.request("GET", "/v2/stores/{storeId}?%s".format(storeId=store_id) % params, "{body}", headers)
        response = conn.getresponse()
        data = response.read()
        print(data)
        conn.close()
    except Exception as e:
        print("[Errno {0}] {1}".format(e.errno, e.strerror))

In [44]:
get_store_info_by_storeid()

b'{"id":"K171","name":"K-MARKET OTANIEMI","update":4262612}'

In [28]:
get_name_by_ean_and_storeid()

b'{"ean":"5060107330368","name":"Ella\'s mansikka-omena 120g 4kk Luomu","group":"13510","price":2.29,"pricingUnit":"kpl","vat":14,"packageSize":"120.00","packageUnit":null,"packageType":"pussi","costCenterId":"TE01","plussaLimited":false,"discountLimited":false,"type":"CONSUMER_GOOD","totalPrice":2.29}'

In [32]:

nutrition_types = {
    'The Beginner Meal Plan': [
        '''Target: 2,500 calories, 218 g carbs, 218 g protein, 83 g fat''',
        '''If you want to stay healthy and have more energy, this is the plan for you.'''
    ],
    'The Skinny Guy Muscle-Gain Plan': [
        '''Target: approx. 3,000 calories, 300 g carbs, 225 g protein, 100 g fat''',
        '''Forging new muscle requires a menu that is high in both carbs and calories.'''
    ],
    'The Get-Lean Meal Plan' : [
        '''Target: 2000 calories, 150 g carbs, 150 g protein, 88 g fat''',
        '''To accelerate your weight loss, limit starchy carbs to the period directly after training.'''
    ], 
    'Vegetarian Balanced Meal Plan' : [
        '''Target: 2200 calories, 250 g carbs, 85 g protein, 80 g fat''',
        '''Balanced plan to stay healty eating vegetarian meals.'''
    ], 
    'Vegan Meal Plan': [
        '''Target: ???''', 
        '''A vegan diet contains only plants (such as vegetables, grains, nuts and fruits) and foods made from plants.'''
    ],
    'Ketogenic Meal Plan' : [
        '''Target: ???''',
        '''The ketogenic diet is a high-fat, adequate-protein, low-carbohydrate diet.'''
    ],
    'Paleo Meal Plan' : [
        '''Target: ???''',
        '''A paleo diet is a dietary plan based on foods similar to what might have been eaten during the Paleolithic era.'''
    ],
    'Fertility Meal Plan': [
        '''Target: ???''',
        '''Eating slow carbs help to minimize insulin resistance, regulate blood sugar, improve fertility and prevent gestational diabetes.'''
    ]
}

In [36]:
plan_names = list(nutrition_types.keys())

In [39]:
plan_names = [
 'The Beginner Meal Plan',
 'The Muscle-Gain Plan',
 'The Get-Lean Meal Plan',
 'Vegetarian Balanced Meal Plan',
 'Vegan Meal Plan',
 'Ketogenic Meal Plan',
 'Paleo Meal Plan',
 'Fertility Meal Plan']

In [40]:
plan_descrs = [
 '''If you want to stay healthy and have more energy, this is the plan for you.''',
 '''Forging new muscle requires a menu that is high in both carbs and calories.''',
 '''To accelerate your weight loss, limit starchy carbs to the period directly after training.''',
 '''Balanced plan to stay healty eating vegetarian meals.''',
 '''A vegan diet contains only plants (such as vegetables, grains, nuts and fruits) and foods made from plants.''',
 '''The ketogenic diet is a high-fat, adequate-protein, low-carbohydrate diet.''',
 '''A paleo diet is a dietary plan based on foods similar to what might have been eaten during the Paleolithic era.''',
 '''Eating slow carbs help to minimize insulin resistance, regulate blood sugar, improve fertility and prevent gestational diabetes.'''
]

In [42]:
beginner_plan = ['Greek Yogurt', 'Raspberries', 'Tomato', 'Beef', 'Beans', 'Spinach', 'Bell pepper', 'Shrimps']
muscle_plan = ['Eggs', 'Almonds', 'Cucumber', 'Red Meat', 'Chickpeas', 'Chicken', 'White fish', 'Broccoli', 'Butter', 'Parmesan Cheese']
lean_plan = ['Eggs', 'Cheese', 'Spinach', 'Chia Seeds', 'Strawberries', 'Steak', 'Avocado', 'Tomato', 'Mushrooms', 'Broccoli']
vegetarian_plan = ['Milk', 'Eggs', 'Bell pepper', 'Carrot', 'Tofu', 'Bananas', 'Corn', 'Brown Rice', 'Avocado', 'Yogurt', 'Brussels sprouts']
vegan_plan = ['Tofu', 'Almond Milk', 'Carrot', 'Brown Rice', 'Broccoli', 'Spinach', 'Asparagus', 'Pasta', 'Cashews', 'Beans']
keto_plan = ['Eggs', 'Cheese', 'Shrimps', 'Red Meat', 'Avocado', 'Broccoli', 'Brazil Nuts', 'Fresh Fish', 'Mushrooms', 'Wallnuts']
paleo_plan = ['Fish', 'Eggs', 'Avocado', 'Broccoli', 'Potato', 'Nuts', 'Mushrooms', 'Diet Soda', ]